version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install react-router-dom
      - npm i -g npm
      - npm install
      - npm install webpack@4.28.4
      - npm install acorn-dynamic-import@4.0.0
      - npm update acorn --depth 20
      - npm dedupe
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: client/build

cache:
  paths:
    - "node_modules/**/*" # Cache `node_modules` for faster `yarn` or `npm i`
    - ".next/cache/**/*" # Cache Next.js for faster application rebuilds
